-- =============================================================================
-- 011_rubric_seed.sql
-- The Hub — Phase 3, migration 11: the live rubric, migrated.
--
-- 77 behaviors, 314 answer options,
-- 12 sections. Generated from the live reviewer_form_points export, not
-- retyped, so nothing drifts in transcription.
--
-- Objective questions come from the Reviewer Form. Impression questions come
-- from Call Tracking Metrics, where the shopper enters them. That division
-- already exists in the live data and is preserved exactly.
--
-- possible_points is the maximum across a question's answer options, which is
-- how the current engine already computes it. Conditional questions therefore
-- keep producing a per-call denominator rather than a fixed total.
--
-- Requires: 001 to 010
-- =============================================================================

BEGIN;

INSERT INTO rubric_templates (name, rubric_type, version, notes)
VALUES ('Dead Ringers CX', 'cx', '2026.09',
        'Migrated from the live BigQuery scoring engine, September 2026')
ON CONFLICT (name, version) DO NOTHING;

-- Objective:   66 questions,    111 points
-- Impression:  11 questions,     29 points
-- Total:       77 questions,    140 points

-- -----------------------------------------------------------------------------
-- behaviors
-- -----------------------------------------------------------------------------
INSERT INTO behaviors (code, label, section_id, score_category, answered_by) VALUES
  ('at_the_end_of_the_call_did_they_thank_you_for_calling_them', 'At the end of the call, did they thank you for calling them?', (SELECT id FROM rubric_sections WHERE code = 'closing'), 'objective', 'reviewer'),
  ('did_the_call_seem_rushed_or_hurried', 'Did the call seem rushed or hurried?', (SELECT id FROM rubric_sections WHERE code = 'closing'), 'objective', 'reviewer'),
  ('did_they_end_the_call_with_a_clear_proper_end_greeting_i_e', 'Did they end the call with a clear, proper end greeting? (i.e., Goodbye, Take care, Thank you)', (SELECT id FROM rubric_sections WHERE code = 'closing'), 'objective', 'reviewer'),
  ('did_they_provide_a_call_to_action_i_e_call_us_back_if_you_', 'Did they provide a call to action? (i.e., Call us back if you have any questions)', (SELECT id FROM rubric_sections WHERE code = 'closing'), 'objective', 'reviewer'),
  ('did_they_repeat_their_name_before_they_ended_the_call', 'Did they repeat their name before they ended the call?', (SELECT id FROM rubric_sections WHERE code = 'closing'), 'objective', 'reviewer'),
  ('did_the_professional_express_condolences_i_e_i_m_sorry_to_', 'Did the professional express condolences? i.e. "I''m sorry to hear that your family member is not doing well."', (SELECT id FROM rubric_sections WHERE code = 'etiquette'), 'objective', 'reviewer'),
  ('did_they_have_any_poor_phone_behaviors_i_e_vocal_fry_uptal', 'Did they have any poor phone behaviors? (i.e. Vocal fry, uptalk, "Um," mouth noises)', (SELECT id FROM rubric_sections WHERE code = 'etiquette'), 'objective', 'reviewer'),
  ('did_they_mention_any_of_their_competitors_at_any_point_dur', 'Did they mention any of their competitors at any point during the call?', (SELECT id FROM rubric_sections WHERE code = 'etiquette'), 'objective', 'reviewer'),
  ('did_they_use_industry_jargon_or_legalese_that_was_unfamili', 'Did they use industry jargon or legalese that was unfamiliar to you?', (SELECT id FROM rubric_sections WHERE code = 'etiquette'), 'objective', 'reviewer'),
  ('did_they_use_your_name_in_conversation', 'Did they use your name in conversation?', (SELECT id FROM rubric_sections WHERE code = 'etiquette'), 'objective', 'reviewer'),
  ('were_they_articulate_and_easy_to_understand', 'Were they articulate and easy to understand?', (SELECT id FROM rubric_sections WHERE code = 'etiquette'), 'objective', 'reviewer'),
  ('at_the_beginning_of_your_conversation_did_they_ask_questio', 'At the beginning of your conversation, did they ask questions about you or your reason for calling?', (SELECT id FROM rubric_sections WHERE code = 'first_engagement'), 'objective', 'reviewer'),
  ('did_the_professional_have_a_proper_greeting', 'Did the professional have a proper greeting?', (SELECT id FROM rubric_sections WHERE code = 'first_engagement'), 'objective', 'reviewer'),
  ('did_they_have_a_proper_greeting', 'Did they have a proper greeting?', (SELECT id FROM rubric_sections WHERE code = 'first_engagement'), 'objective', 'reviewer'),
  ('did_they_ask_if_you_had_any_other_questions', 'Did they ask if you had any other questions?', (SELECT id FROM rubric_sections WHERE code = 'follow_up'), 'objective', 'reviewer'),
  ('did_they_attempt_to_set_an_appointment_invite_you_to_visit', 'Did they attempt to set an appointment, invite you to visit their location, or bring your loved one into their care?', (SELECT id FROM rubric_sections WHERE code = 'follow_up'), 'objective', 'reviewer'),
  ('did_they_offer_to_call_you_back_at_a_later_time_to_follow_', 'Did they offer to call you back at a later time to follow up?', (SELECT id FROM rubric_sections WHERE code = 'follow_up'), 'objective', 'reviewer'),
  ('did_they_offer_to_mail_or_email_information_to_you', 'Did they offer to mail or email information to you?', (SELECT id FROM rubric_sections WHERE code = 'follow_up'), 'objective', 'reviewer'),
  ('did_they_provide_their_direct_phone_number_or_email_before', 'Did they provide their direct phone number or email before they ended the call?', (SELECT id FROM rubric_sections WHERE code = 'follow_up'), 'objective', 'reviewer'),
  ('did_they_refer_to_their_website', 'Did they refer to their website?', (SELECT id FROM rubric_sections WHERE code = 'follow_up'), 'objective', 'reviewer'),
  ('did_you_receive_an_email_from_the_professional', 'Did you receive an email from the professional?', (SELECT id FROM rubric_sections WHERE code = 'follow_up'), 'objective', 'reviewer'),
  ('did_anyone_check_back_with_you_while_you_were_on_hold', 'Did anyone check back with you while you were on hold?', (SELECT id FROM rubric_sections WHERE code = 'hold_transfer'), 'objective', 'reviewer'),
  ('did_they_ask_for_permission_to_place_you_on_hold', 'Did they ask for permission to place you on hold?', (SELECT id FROM rubric_sections WHERE code = 'hold_transfer'), 'objective', 'reviewer'),
  ('did_they_explain_why_they_were_placing_you_on_hold_or_set_', 'Did they explain why they were placing you on hold, or set expectations for the hold?', (SELECT id FROM rubric_sections WHERE code = 'hold_transfer'), 'objective', 'reviewer'),
  ('did_you_have_to_repeat_any_of_your_information_to_the_new_', 'Did you have to repeat any of your information to the new professional?', (SELECT id FROM rubric_sections WHERE code = 'hold_transfer'), 'objective', 'reviewer'),
  ('how_long_were_you_on_hold', 'How long were you on hold?', (SELECT id FROM rubric_sections WHERE code = 'hold_transfer'), 'objective', 'reviewer'),
  ('was_there_any_music_or_message_on_hold', 'Was there any music or message on hold?', (SELECT id FROM rubric_sections WHERE code = 'hold_transfer'), 'objective', 'reviewer'),
  ('were_you_placed_on_hold_and_or_transferred_more_than_once', 'Were you placed on hold and/or transferred more than once?', (SELECT id FROM rubric_sections WHERE code = 'hold_transfer'), 'objective', 'reviewer'),
  ('were_you_placed_on_hold_before_you_had_the_opportunity_to_', 'Were you placed on hold before you had the opportunity to ask your question?', (SELECT id FROM rubric_sections WHERE code = 'hold_transfer'), 'objective', 'reviewer'),
  ('were_you_placed_on_hold_or_transferred_at_any_point_within', 'Were you placed on hold or transferred at any point within the call?', (SELECT id FROM rubric_sections WHERE code = 'hold_transfer'), 'objective', 'reviewer'),
  ('were_you_transferred_to_voicemail_or_to_a_live_agent', 'Were you transferred to voicemail, or to a live agent?', (SELECT id FROM rubric_sections WHERE code = 'hold_transfer'), 'objective', 'reviewer'),
  ('did_they_identify_themselves_as_an_answering_service', 'Did they identify themselves as an Answering Service?', (SELECT id FROM rubric_sections WHERE code = 'initial_answer'), 'objective', 'reviewer'),
  ('did_you_receive_a_callback_from_a_professional', 'Did you receive a callback from a professional?', (SELECT id FROM rubric_sections WHERE code = 'initial_answer'), 'objective', 'reviewer'),
  ('how_long_did_it_take_for_the_professional_to_provide_a_cal', 'How long did it take for the professional to provide a callback?', (SELECT id FROM rubric_sections WHERE code = 'initial_answer'), 'objective', 'reviewer'),
  ('how_many_attempts_did_it_take_to_reach_a_professional_who_', 'How many attempts did it take to reach a professional who could answer your questions?', (SELECT id FROM rubric_sections WHERE code = 'initial_answer'), 'objective', 'reviewer'),
  ('how_many_prompts_did_you_have_to_go_through_before_you_wer', 'How many prompts did you have to go through before you were transferred to a live representative?', (SELECT id FROM rubric_sections WHERE code = 'initial_answer'), 'objective', 'reviewer'),
  ('how_many_times_did_the_phone_ring', 'How many times did the phone ring?', (SELECT id FROM rubric_sections WHERE code = 'initial_answer'), 'objective', 'reviewer'),
  ('if_a_professional_was_unavailable_to_answer_your_questions', 'If a professional was unavailable to answer your questions, how did the receptionist handle the situation?', (SELECT id FROM rubric_sections WHERE code = 'initial_answer'), 'objective', 'reviewer'),
  ('were_any_of_your_call_attempts_answered_initially_by_an_au', 'Were any of your call attempts answered initially by an automated message?', (SELECT id FROM rubric_sections WHERE code = 'initial_answer'), 'objective', 'reviewer'),
  ('were_you_able_to_have_your_questions_answered_on_this_call', 'Were you able to have your questions answered on this call?', (SELECT id FROM rubric_sections WHERE code = 'initial_answer'), 'objective', 'reviewer'),
  ('why_were_you_unable_to_have_your_questions_answered_on_thi', 'Why were you unable to have your questions answered on this callback?', (SELECT id FROM rubric_sections WHERE code = 'initial_answer'), 'objective', 'reviewer'),
  ('why_were_you_unable_to_reach_a_professional_on_this_first_', 'Why were you unable to reach a professional on this first attempt?', (SELECT id FROM rubric_sections WHERE code = 'initial_answer'), 'objective', 'reviewer'),
  ('did_the_professional_ask_your_relationship_to_the_decedent', 'Did the professional ask your relationship to the decedent/your loved one?', (SELECT id FROM rubric_sections WHERE code = 'lead_information'), 'objective', 'reviewer'),
  ('did_the_professional_provide_their_name', 'Did the professional provide their name?', (SELECT id FROM rubric_sections WHERE code = 'lead_information'), 'objective', 'reviewer'),
  ('did_they_ask_for_the_name_of_your_loved_one', 'Did they ask for the name of your loved one?', (SELECT id FROM rubric_sections WHERE code = 'lead_information'), 'objective', 'reviewer'),
  ('did_they_ask_for_your_email_address', 'Did they ask for your email address?', (SELECT id FROM rubric_sections WHERE code = 'lead_information'), 'objective', 'reviewer'),
  ('did_they_ask_for_your_location_or_the_location_of_your_lov', 'Did they ask for your location or the location of your loved one?', (SELECT id FROM rubric_sections WHERE code = 'lead_information'), 'objective', 'reviewer'),
  ('did_they_ask_for_your_name', 'Did they ask for your name?', (SELECT id FROM rubric_sections WHERE code = 'lead_information'), 'objective', 'reviewer'),
  ('did_they_ask_for_your_phone_number', 'Did they ask for your phone number?', (SELECT id FROM rubric_sections WHERE code = 'lead_information'), 'objective', 'reviewer'),
  ('did_they_ask_how_you_heard_about_their_business', 'Did they ask how you heard about their business?', (SELECT id FROM rubric_sections WHERE code = 'lead_information'), 'objective', 'reviewer'),
  ('did_they_ask_if_the_death_had_occurred', 'Did they ask if the death had occurred?', (SELECT id FROM rubric_sections WHERE code = 'lead_information'), 'objective', 'reviewer'),
  ('did_they_ask_if_you_had_visited_their_location_or_utilized', 'Did they ask if you had visited their location or utilized their services in the past?', (SELECT id FROM rubric_sections WHERE code = 'lead_information'), 'objective', 'reviewer'),
  ('did_they_require_your_name_and_or_contact_information_befo', 'Did they REQUIRE your name and/or contact information before they would provide pricing information?', (SELECT id FROM rubric_sections WHERE code = 'lead_information'), 'objective', 'reviewer'),
  ('did_the_professional_mention_an_alternative_container_or_c', 'Did the professional mention an “alternative container” or "cremation casket"?', (SELECT id FROM rubric_sections WHERE code = 'services_pricing'), 'objective', 'reviewer'),
  ('did_the_professional_mention_any_preservative_warranties_o', 'Did the professional mention any preservative warranties on any funeral products?', (SELECT id FROM rubric_sections WHERE code = 'services_pricing'), 'objective', 'reviewer'),
  ('did_they_ask_you_about_what_services_you_are_interested_in', 'Did they ask you about what services you are interested in?', (SELECT id FROM rubric_sections WHERE code = 'services_pricing'), 'objective', 'reviewer'),
  ('did_they_explain_what_was_included_in_the_prices_they_prov', 'Did they explain what was included in the prices they provided?', (SELECT id FROM rubric_sections WHERE code = 'services_pricing'), 'objective', 'reviewer'),
  ('did_they_explain_why_their_business_is_unique', 'Did they explain why their business is unique?', (SELECT id FROM rubric_sections WHERE code = 'services_pricing'), 'objective', 'reviewer'),
  ('did_they_mention_embalming_and_or_refrigeration', 'Did they mention Embalming and/or Refrigeration?', (SELECT id FROM rubric_sections WHERE code = 'services_pricing'), 'objective', 'reviewer'),
  ('did_they_offer_any_discounts', 'Did they offer any discounts?', (SELECT id FROM rubric_sections WHERE code = 'services_pricing'), 'objective', 'reviewer'),
  ('did_they_offer_multiple_service_options', 'Did they offer multiple service options?', (SELECT id FROM rubric_sections WHERE code = 'services_pricing'), 'objective', 'reviewer'),
  ('did_they_provide_pricing', 'Did they provide pricing?', (SELECT id FROM rubric_sections WHERE code = 'services_pricing'), 'objective', 'reviewer'),
  ('did_they_provide_the_lowest_cost_option_first', 'Did they provide the lowest cost option first?', (SELECT id FROM rubric_sections WHERE code = 'services_pricing'), 'objective', 'reviewer'),
  ('did_they_seem_educated_and_knowledgable_about_the_services', 'Did they seem educated and knowledgable about the services they offered?', (SELECT id FROM rubric_sections WHERE code = 'services_pricing'), 'objective', 'reviewer'),
  ('did_they_sound_comfortable_and_confident_with_providing_se', 'Did they sound comfortable and confident with providing service information and pricing?', (SELECT id FROM rubric_sections WHERE code = 'services_pricing'), 'objective', 'reviewer'),
  ('when_describing_services_did_they_give_a_reason_for_their_', 'When describing services, did they give a reason for their value or attempt to upsell?', (SELECT id FROM rubric_sections WHERE code = 'services_pricing'), 'objective', 'reviewer'),
  ('custom_fields_did_they_seem_prepared', 'custom_fields_did_they_seem_prepared', (SELECT id FROM rubric_sections WHERE code = 'accessibility'), 'impression', 'shopper'),
  ('custom_fields_ease_of_reaching_right_person', 'custom_fields_ease_of_reaching_right_person', (SELECT id FROM rubric_sections WHERE code = 'accessibility'), 'impression', 'shopper'),
  ('custom_fields_expectations', 'custom_fields_expectations', (SELECT id FROM rubric_sections WHERE code = 'buy_in'), 'impression', 'shopper'),
  ('custom_fields_how_would_you_rate_the_call', 'custom_fields_how_would_you_rate_the_call', (SELECT id FROM rubric_sections WHERE code = 'buy_in'), 'impression', 'shopper'),
  ('custom_fields_would_you_hire_this_company', 'custom_fields_would_you_hire_this_company', (SELECT id FROM rubric_sections WHERE code = 'buy_in'), 'impression', 'shopper'),
  ('custom_fields_would_you_hire_this_person', 'custom_fields_would_you_hire_this_person', (SELECT id FROM rubric_sections WHERE code = 'buy_in'), 'impression', 'shopper'),
  ('custom_fields_enough_information', 'custom_fields_enough_information', (SELECT id FROM rubric_sections WHERE code = 'clarity'), 'impression', 'shopper'),
  ('custom_fields_were_they_clear_concise', 'custom_fields_were_they_clear_concise', (SELECT id FROM rubric_sections WHERE code = 'clarity'), 'impression', 'shopper'),
  ('custom_fields_etiquette_adjectives', 'custom_fields_etiquette_adjectives', (SELECT id FROM rubric_sections WHERE code = 'sincerity'), 'impression', 'shopper'),
  ('custom_fields_sincere_concern', 'custom_fields_sincere_concern', (SELECT id FROM rubric_sections WHERE code = 'sincerity'), 'impression', 'shopper'),
  ('custom_fields_would_you_trust_them', 'custom_fields_would_you_trust_them', (SELECT id FROM rubric_sections WHERE code = 'sincerity'), 'impression', 'shopper')
ON CONFLICT (code) DO NOTHING;

-- -----------------------------------------------------------------------------
-- behavior_answers — points live on the option, which is what makes the
-- FTC verdict a formula rather than a judgment
-- -----------------------------------------------------------------------------
INSERT INTO behavior_answers (behavior_id, answer_value, points, counts_as_observed, ftc_flag, display_order) VALUES
  ((SELECT id FROM behaviors WHERE code = 'at_the_end_of_the_call_did_they_thank_you_for_calling_them'), 'Yes', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'at_the_end_of_the_call_did_they_thank_you_for_calling_them'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_the_call_seem_rushed_or_hurried'), 'Yes', 0.0, false, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_the_call_seem_rushed_or_hurried'), 'No', 1.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_end_the_call_with_a_clear_proper_end_greeting_i_e'), 'Yes', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_end_the_call_with_a_clear_proper_end_greeting_i_e'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_provide_a_call_to_action_i_e_call_us_back_if_you_'), 'Yes', 1.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_provide_a_call_to_action_i_e_call_us_back_if_you_'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_repeat_their_name_before_they_ended_the_call'), 'Yes', 1.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_repeat_their_name_before_they_ended_the_call'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_the_professional_express_condolences_i_e_i_m_sorry_to_'), 'Yes', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_the_professional_express_condolences_i_e_i_m_sorry_to_'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_have_any_poor_phone_behaviors_i_e_vocal_fry_uptal'), 'None', 3.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_have_any_poor_phone_behaviors_i_e_vocal_fry_uptal'), 'Talked too fast/slow', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_have_any_poor_phone_behaviors_i_e_vocal_fry_uptal'), 'Tone of voice', 0.0, false, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'did_they_have_any_poor_phone_behaviors_i_e_vocal_fry_uptal'), 'Um/filler words', 0.0, false, NULL, 4),
  ((SELECT id FROM behaviors WHERE code = 'did_they_have_any_poor_phone_behaviors_i_e_vocal_fry_uptal'), 'Background noise', 0.0, false, NULL, 5),
  ((SELECT id FROM behaviors WHERE code = 'did_they_have_any_poor_phone_behaviors_i_e_vocal_fry_uptal'), 'Mouth noise', 0.0, false, NULL, 6),
  ((SELECT id FROM behaviors WHERE code = 'did_they_have_any_poor_phone_behaviors_i_e_vocal_fry_uptal'), 'Scripted/robotic', 0.0, false, NULL, 7),
  ((SELECT id FROM behaviors WHERE code = 'did_they_mention_any_of_their_competitors_at_any_point_dur'), 'Yes', 0.0, false, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_mention_any_of_their_competitors_at_any_point_dur'), 'No', 1.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_use_industry_jargon_or_legalese_that_was_unfamili'), 'Yes, and they explained the meaning', 1.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_use_industry_jargon_or_legalese_that_was_unfamili'), 'Yes, but they did not explain', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_use_industry_jargon_or_legalese_that_was_unfamili'), 'No, they didn''t use any unfamiliar terms.', 1.0, true, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'did_they_use_your_name_in_conversation'), 'Yes, throughout the conversation', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_use_your_name_in_conversation'), 'Yes, only at the beginning or the end', 1.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_use_your_name_in_conversation'), 'No', 0.0, false, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'were_they_articulate_and_easy_to_understand'), 'Yes', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'were_they_articulate_and_easy_to_understand'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'at_the_beginning_of_your_conversation_did_they_ask_questio'), 'Yes, they asked the right questions to determine the best way to serve me', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'at_the_beginning_of_your_conversation_did_they_ask_questio'), 'Yes, they asked some questions but could/should have asked more', 1.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'at_the_beginning_of_your_conversation_did_they_ask_questio'), 'No, they made assumptions about what I needed', 0.0, false, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'at_the_beginning_of_your_conversation_did_they_ask_questio'), 'No, they did not ask questions', 0.0, false, NULL, 4),
  ((SELECT id FROM behaviors WHERE code = 'did_the_professional_have_a_proper_greeting'), 'Thank you for calling', 1.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_the_professional_have_a_proper_greeting'), 'Location name', 1.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_the_professional_have_a_proper_greeting'), 'Their name', 1.0, true, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'did_the_professional_have_a_proper_greeting'), 'Value/buffer statement', 1.0, true, NULL, 4),
  ((SELECT id FROM behaviors WHERE code = 'did_the_professional_have_a_proper_greeting'), 'No greeting', 0.0, false, NULL, 5),
  ((SELECT id FROM behaviors WHERE code = 'did_they_have_a_proper_greeting'), 'Thank you for calling', 1.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_have_a_proper_greeting'), 'Location name', 1.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_have_a_proper_greeting'), 'Their name', 1.0, true, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'did_they_have_a_proper_greeting'), 'Value/buffer statement', 1.0, true, NULL, 4),
  ((SELECT id FROM behaviors WHERE code = 'did_they_have_a_proper_greeting'), 'No greeting', 0.0, false, NULL, 5),
  ((SELECT id FROM behaviors WHERE code = 'did_they_ask_if_you_had_any_other_questions'), 'Yes', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_ask_if_you_had_any_other_questions'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_attempt_to_set_an_appointment_invite_you_to_visit'), 'Yes', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_attempt_to_set_an_appointment_invite_you_to_visit'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_offer_to_call_you_back_at_a_later_time_to_follow_'), 'Yes', 1.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_offer_to_call_you_back_at_a_later_time_to_follow_'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_offer_to_mail_or_email_information_to_you'), 'Yes, the professional offered to email information instead of providing pricing information over the phone.', 0.0, false, 'red', 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_offer_to_mail_or_email_information_to_you'), 'Yes, the professional offered to email information in addition to providing pricing information over the phone.', 2.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_offer_to_mail_or_email_information_to_you'), 'No', 0.0, false, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'did_they_provide_their_direct_phone_number_or_email_before'), 'Yes', 1.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_provide_their_direct_phone_number_or_email_before'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_refer_to_their_website'), 'YES, the professional referred to the website in place of providing pricing information over the phone.', 0.0, false, 'red', 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_refer_to_their_website'), 'YES, the professional referred to the website in addition to providing pricing information over the phone.', 1.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_refer_to_their_website'), 'No', 0.0, false, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'did_you_receive_an_email_from_the_professional'), 'Yes, they emailed the information they had promised.', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_you_receive_an_email_from_the_professional'), 'Yes, they emailed, but provided different information than was promised.', 1.0, true, 'yellow', 2),
  ((SELECT id FROM behaviors WHERE code = 'did_you_receive_an_email_from_the_professional'), 'No, they did not email', 0.0, false, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'did_anyone_check_back_with_you_while_you_were_on_hold'), 'Yes', 1.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_anyone_check_back_with_you_while_you_were_on_hold'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_ask_for_permission_to_place_you_on_hold'), 'Yes', 1.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_ask_for_permission_to_place_you_on_hold'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_explain_why_they_were_placing_you_on_hold_or_set_'), 'Yes', 1.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_explain_why_they_were_placing_you_on_hold_or_set_'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_you_have_to_repeat_any_of_your_information_to_the_new_'), 'Yes - Cold transfer', 0.0, false, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_you_have_to_repeat_any_of_your_information_to_the_new_'), 'No - Warm transfer', 2.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'how_long_were_you_on_hold'), '0–10 seconds', 5.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'how_long_were_you_on_hold'), '10-30 seconds', 3.75, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'how_long_were_you_on_hold'), '30-60 seconds', 1.25, true, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'how_long_were_you_on_hold'), 'Over 60 seconds', 0.0, false, NULL, 4),
  ((SELECT id FROM behaviors WHERE code = 'was_there_any_music_or_message_on_hold'), 'Silence', 0.0, false, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'was_there_any_music_or_message_on_hold'), 'Beeps', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'was_there_any_music_or_message_on_hold'), 'Music', 0.0, false, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'was_there_any_music_or_message_on_hold'), 'Message / Advertisement', 0.0, false, NULL, 4),
  ((SELECT id FROM behaviors WHERE code = 'were_you_placed_on_hold_and_or_transferred_more_than_once'), 'Yes', 0.0, false, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'were_you_placed_on_hold_and_or_transferred_more_than_once'), 'No', 2.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'were_you_placed_on_hold_before_you_had_the_opportunity_to_'), 'Yes', 0.0, false, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'were_you_placed_on_hold_before_you_had_the_opportunity_to_'), 'No', 1.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'were_you_placed_on_hold_or_transferred_at_any_point_within'), 'Yes, placed on hold and transferred', 0.0, false, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'were_you_placed_on_hold_or_transferred_at_any_point_within'), 'Yes, placed on hold', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'were_you_placed_on_hold_or_transferred_at_any_point_within'), 'No, never placed on hold or transferred', 5.0, true, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'were_you_transferred_to_voicemail_or_to_a_live_agent'), 'Transferred to voicemail', 0.0, false, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'were_you_transferred_to_voicemail_or_to_a_live_agent'), 'Transferred to a professional', 2.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_identify_themselves_as_an_answering_service'), 'Yes', 0.0, false, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_identify_themselves_as_an_answering_service'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_you_receive_a_callback_from_a_professional'), 'Yes', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_you_receive_a_callback_from_a_professional'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'how_long_did_it_take_for_the_professional_to_provide_a_cal'), '0-3 Hours', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'how_long_did_it_take_for_the_professional_to_provide_a_cal'), '3-12 Hours', 1.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'how_long_did_it_take_for_the_professional_to_provide_a_cal'), '12-24 Hours', 0.5, true, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'how_long_did_it_take_for_the_professional_to_provide_a_cal'), 'Over 24 Hours', 0.0, false, NULL, 4),
  ((SELECT id FROM behaviors WHERE code = 'how_many_attempts_did_it_take_to_reach_a_professional_who_'), 'Reached a professional on the first attempt', 5.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'how_many_attempts_did_it_take_to_reach_a_professional_who_'), 'Reached a professional on the second attempt', 2.5, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'how_many_attempts_did_it_take_to_reach_a_professional_who_'), 'Reached a professional after more than two attempts', 0.5, true, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'how_many_attempts_did_it_take_to_reach_a_professional_who_'), 'Accepted a callback from a professional', 2.5, true, NULL, 4),
  ((SELECT id FROM behaviors WHERE code = 'how_many_attempts_did_it_take_to_reach_a_professional_who_'), 'Never reached a professional', 0.0, false, NULL, 5),
  ((SELECT id FROM behaviors WHERE code = 'how_many_prompts_did_you_have_to_go_through_before_you_wer'), '0 - Transferred automatically', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'how_many_prompts_did_you_have_to_go_through_before_you_wer'), '1', 1.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'how_many_prompts_did_you_have_to_go_through_before_you_wer'), '2', 0.0, false, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'how_many_prompts_did_you_have_to_go_through_before_you_wer'), '3+', 0.0, false, NULL, 4),
  ((SELECT id FROM behaviors WHERE code = 'how_many_prompts_did_you_have_to_go_through_before_you_wer'), 'Unable to reach a live representative', 0.0, false, NULL, 5),
  ((SELECT id FROM behaviors WHERE code = 'how_many_times_did_the_phone_ring'), '1', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'how_many_times_did_the_phone_ring'), '2', 1.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'how_many_times_did_the_phone_ring'), '3', 1.0, true, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'how_many_times_did_the_phone_ring'), '4', 0.0, false, NULL, 4),
  ((SELECT id FROM behaviors WHERE code = 'how_many_times_did_the_phone_ring'), '5+', 0.0, false, NULL, 5),
  ((SELECT id FROM behaviors WHERE code = 'how_many_times_did_the_phone_ring'), 'No Answer or Voicemail', 0.0, false, NULL, 6),
  ((SELECT id FROM behaviors WHERE code = 'if_a_professional_was_unavailable_to_answer_your_questions'), 'Answered questions to the best of their ability', 1.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'if_a_professional_was_unavailable_to_answer_your_questions'), 'Asked for name and number for professional to call back', 1.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'if_a_professional_was_unavailable_to_answer_your_questions'), 'Asked further questions about caller''s situation and needs', 1.0, true, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'if_a_professional_was_unavailable_to_answer_your_questions'), 'Offered to send information via email', 1.0, true, NULL, 4),
  ((SELECT id FROM behaviors WHERE code = 'if_a_professional_was_unavailable_to_answer_your_questions'), 'Instructed caller to call back at a later time', 0.0, false, NULL, 5),
  ((SELECT id FROM behaviors WHERE code = 'if_a_professional_was_unavailable_to_answer_your_questions'), 'Provided alternate number for caller to call', 0.0, false, NULL, 6),
  ((SELECT id FROM behaviors WHERE code = 'if_a_professional_was_unavailable_to_answer_your_questions'), 'Referred caller to alternate location for service', 0.0, false, NULL, 7),
  ((SELECT id FROM behaviors WHERE code = 'if_a_professional_was_unavailable_to_answer_your_questions'), 'Nothing—Receptionist did not provide options to get in touch with professional', 0.0, false, NULL, 8),
  ((SELECT id FROM behaviors WHERE code = 'were_any_of_your_call_attempts_answered_initially_by_an_au'), 'Yes', 0.0, false, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'were_any_of_your_call_attempts_answered_initially_by_an_au'), 'No', 2.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'were_you_able_to_have_your_questions_answered_on_this_call'), 'Yes', 0.0, false, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'were_you_able_to_have_your_questions_answered_on_this_call'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'were_you_able_to_have_your_questions_answered_on_this_call'), 'Call disconnected during transfer', 0.0, false, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'were_you_able_to_have_your_questions_answered_on_this_call'), 'Call transferred to voicemail', 0.0, false, NULL, 4),
  ((SELECT id FROM behaviors WHERE code = 'why_were_you_unable_to_have_your_questions_answered_on_thi'), 'Call disconnected when answered', 0.0, false, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'why_were_you_unable_to_have_your_questions_answered_on_thi'), 'Professional unavailable to answer questions', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'why_were_you_unable_to_reach_a_professional_on_this_first_'), 'Call not answered', 0.0, false, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'why_were_you_unable_to_reach_a_professional_on_this_first_'), 'Could not navigate automated menu', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'why_were_you_unable_to_reach_a_professional_on_this_first_'), 'Call disconnected when answered', 0.0, false, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'why_were_you_unable_to_reach_a_professional_on_this_first_'), 'Call disconnected during transfer', 0.0, false, NULL, 4),
  ((SELECT id FROM behaviors WHERE code = 'why_were_you_unable_to_reach_a_professional_on_this_first_'), 'Call transferred to voicemail', 0.0, false, NULL, 5),
  ((SELECT id FROM behaviors WHERE code = 'why_were_you_unable_to_reach_a_professional_on_this_first_'), 'Call answered by an Answering Service', 0.0, false, NULL, 6),
  ((SELECT id FROM behaviors WHERE code = 'why_were_you_unable_to_reach_a_professional_on_this_first_'), 'Professional unavailable to answer questions', 0.0, false, NULL, 7),
  ((SELECT id FROM behaviors WHERE code = 'did_the_professional_ask_your_relationship_to_the_decedent'), 'Yes', 1.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_the_professional_ask_your_relationship_to_the_decedent'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_the_professional_provide_their_name'), 'Yes, at the beginning of the call', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_the_professional_provide_their_name'), 'Yes, in the middle of the call', 1.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_the_professional_provide_their_name'), 'Yes, but only at the very end', 0.0, false, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'did_the_professional_provide_their_name'), 'No, they never said their name', 0.0, false, NULL, 4),
  ((SELECT id FROM behaviors WHERE code = 'did_they_ask_for_the_name_of_your_loved_one'), 'Yes, within the first half of the call', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_ask_for_the_name_of_your_loved_one'), 'Yes, in the back half of the call', 1.5, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_ask_for_the_name_of_your_loved_one'), 'No', 0.0, false, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'did_they_ask_for_your_email_address'), 'Yes', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_ask_for_your_email_address'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_ask_for_your_location_or_the_location_of_your_lov'), 'Yes', 1.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_ask_for_your_location_or_the_location_of_your_lov'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_ask_for_your_name'), 'Yes, at the beginning of the call', 4.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_ask_for_your_name'), 'Yes, in the middle of the call', 2.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_ask_for_your_name'), 'Yes, but only at the very end', 1.0, true, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'did_they_ask_for_your_name'), 'No, they never asked my name', 0.0, false, NULL, 4),
  ((SELECT id FROM behaviors WHERE code = 'did_they_ask_for_your_phone_number'), 'Yes', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_ask_for_your_phone_number'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_ask_how_you_heard_about_their_business'), 'Yes', 1.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_ask_how_you_heard_about_their_business'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_ask_if_the_death_had_occurred'), 'Yes', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_ask_if_the_death_had_occurred'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_ask_if_you_had_visited_their_location_or_utilized'), 'Yes', 1.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_ask_if_you_had_visited_their_location_or_utilized'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_require_your_name_and_or_contact_information_befo'), 'YES - lead information was required before prices were shared.', 0.0, false, 'red', 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_require_your_name_and_or_contact_information_befo'), 'NO - lead information was requested but not required before prices were shared.', 1.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_require_your_name_and_or_contact_information_befo'), 'NO - lead information was not requested and/or pricing was not given.', 0.0, false, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'did_the_professional_mention_an_alternative_container_or_c'), 'YES, the professional stated the caller was required to buy an alternative container from them', 0.0, false, 'red', 1),
  ((SELECT id FROM behaviors WHERE code = 'did_the_professional_mention_an_alternative_container_or_c'), 'NO, the professional mentioned the alternative container but did not present it as a requirement to purchase, or mentioned the caller could provide their own', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_the_professional_mention_an_alternative_container_or_c'), 'NO, the professional did not mention the alternative container', 0.0, false, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'did_the_professional_mention_any_preservative_warranties_o'), 'YES, the professional made statements such as This casket/vault will prevent the body from natural decomposition', 0.0, false, 'red', 1),
  ((SELECT id FROM behaviors WHERE code = 'did_the_professional_mention_any_preservative_warranties_o'), 'NO, the professional did not make any statements regarding preservative qualities of funeral products.', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_ask_you_about_what_services_you_are_interested_in'), 'Yes, they asked about my interests', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_ask_you_about_what_services_you_are_interested_in'), 'No, they made assumptions about my interests', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_ask_you_about_what_services_you_are_interested_in'), 'No, they didn''t ask about my interests', 0.0, false, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'did_they_explain_what_was_included_in_the_prices_they_prov'), 'Yes', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_explain_what_was_included_in_the_prices_they_prov'), 'No', 0.0, false, 'red', 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_explain_why_their_business_is_unique'), 'Yes, they did a great job of toting their value', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_explain_why_their_business_is_unique'), 'Yes, they mentioned it in passing', 1.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_explain_why_their_business_is_unique'), 'No, there was no value statement', 0.0, false, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'did_they_mention_embalming_and_or_refrigeration'), 'NO, neither embalming nor refrigeration were mentioned', 1.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_mention_embalming_and_or_refrigeration'), 'YES, the professional presented embalming as a requirement', 0.0, false, 'red', 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_mention_embalming_and_or_refrigeration'), 'YES, the professional presented embalming and/or refrigeration as options', 1.0, true, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'did_they_offer_any_discounts'), 'Package Price Discount', 0.0, false, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_offer_any_discounts'), 'Military', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_offer_any_discounts'), 'Trauma Case', 0.0, false, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'did_they_offer_any_discounts'), 'Special Circumstance', 0.0, false, NULL, 4),
  ((SELECT id FROM behaviors WHERE code = 'did_they_offer_any_discounts'), 'Price Matching Competitors', 0.0, false, 'yellow', 5),
  ((SELECT id FROM behaviors WHERE code = 'did_they_offer_any_discounts'), 'Base Service Fee Reduction', 0.0, false, 'red', 6),
  ((SELECT id FROM behaviors WHERE code = 'did_they_offer_any_discounts'), 'No', 0.0, false, NULL, 7),
  ((SELECT id FROM behaviors WHERE code = 'did_they_offer_multiple_service_options'), 'Yes', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_offer_multiple_service_options'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_provide_pricing'), 'Exact Prices', 3.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_provide_pricing'), 'Price Range', 3.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_provide_pricing'), 'Estimate', 1.0, true, 'yellow', 3),
  ((SELECT id FROM behaviors WHERE code = 'did_they_provide_pricing'), 'No pricing', 0.0, false, 'yellow', 4),
  ((SELECT id FROM behaviors WHERE code = 'did_they_provide_the_lowest_cost_option_first'), 'Yes', 0.0, false, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_provide_the_lowest_cost_option_first'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_provide_the_lowest_cost_option_first'), 'Not applicable — they only gave one price or did not provide pricing.', 0.0, false, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'did_they_seem_educated_and_knowledgable_about_the_services'), 'Yes', 1.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_seem_educated_and_knowledgable_about_the_services'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'did_they_sound_comfortable_and_confident_with_providing_se'), 'Yes', 1.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'did_they_sound_comfortable_and_confident_with_providing_se'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'when_describing_services_did_they_give_a_reason_for_their_'), 'Yes', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'when_describing_services_did_they_give_a_reason_for_their_'), 'No', 0.0, false, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_did_they_seem_prepared'), 'They were on top of things, for sure.', 3.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_did_they_seem_prepared'), 'They needed some warming up, but it was fine.', 2.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_did_they_seem_prepared'), 'They could use further training/seemed unprepared.', 1.0, true, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_did_they_seem_prepared'), 'It was uncomfortable/frustrating.', 0.0, false, NULL, 4),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_ease_of_reaching_right_person'), 'Very easy!', 5.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_ease_of_reaching_right_person'), 'Fairly easy.', 4.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_ease_of_reaching_right_person'), 'Satisfactory.', 2.0, true, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_ease_of_reaching_right_person'), 'Somewhat difficult.', 1.0, true, NULL, 4),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_ease_of_reaching_right_person'), 'Very difficult.', 0.0, false, NULL, 5),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_ease_of_reaching_right_person'), 'Extremely difficult/impossible! ', 0.0, false, NULL, 6),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_expectations'), 'This interaction exceeded my expectations!', 3.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_expectations'), 'This interaction met my expectations.', 2.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_expectations'), 'This interaction was below my expectations.', 0.0, false, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_expectations'), 'This interaction was far below my expectations!', 0.0, false, NULL, 4),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_how_would_you_rate_the_call'), '1', 0.0, false, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_how_would_you_rate_the_call'), '2', 1.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_how_would_you_rate_the_call'), '3', 2.0, true, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_how_would_you_rate_the_call'), '4', 4.0, true, NULL, 4),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_how_would_you_rate_the_call'), '5', 5.0, true, NULL, 5),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_would_you_hire_this_company'), 'Yes - I would feel confident choosing this company.', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_would_you_hire_this_company'), 'Maybe - I would consider other options first.', 1.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_would_you_hire_this_company'), 'No - I would not use this company. ', 0.0, false, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_would_you_hire_this_person'), 'Yes - This person did a great job on the phone.', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_would_you_hire_this_person'), 'Maybe - The person could do well with further training.', 1.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_would_you_hire_this_person'), 'No - This person does not do well on the phone.', 0.0, false, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_enough_information'), 'Yes - I could easily make a decision based on the scope of information provided.', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_enough_information'), 'Maybe - They offered access to further information that would help.', 1.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_enough_information'), 'Maybe - I would consider other options before choosing this company.', 1.0, true, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_enough_information'), 'No - I did not receive the information I would need to confidently choose this company. ', 0.0, false, NULL, 4),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_were_they_clear_concise'), 'Yes - I understood and appreciated all information provided.', 3.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_were_they_clear_concise'), 'Yes - but it was a little overwhelming.', 2.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_were_they_clear_concise'), 'Yes - but I would have liked more information.', 2.0, true, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_were_they_clear_concise'), 'No - they did not seem confident in their knowledge.', 1.0, true, NULL, 4),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_were_they_clear_concise'), 'No - they did not provide details in a way that was easy for me to understand.', 1.0, true, NULL, 5),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_were_they_clear_concise'), 'No details provided.', 0.0, false, NULL, 6),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_etiquette_adjectives'), 'Empathetic | Kind | Soft-spoken | Confident | Happy | Fast | Loud | Bold | Pushy | Sales-oriented | Flat | Annoying | Rude | Off-putting | Disengaged/Aloof', 0.0, false, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_sincere_concern'), 'Yes - I believe the professional genuinely cared for my situation.', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_sincere_concern'), 'Maybe - The professional could have connected better.', 1.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_sincere_concern'), 'No - I do not believe the professional cared for my situation.', 0.0, false, NULL, 3),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_would_you_trust_them'), 'Yes - I would trust this company to serve me at the highest level.', 2.0, true, NULL, 1),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_would_you_trust_them'), 'Maybe - I would have reservations.', 1.0, true, NULL, 2),
  ((SELECT id FROM behaviors WHERE code = 'custom_fields_would_you_trust_them'), 'No - I would not trust this company to provide the best level of service.', 0.0, false, NULL, 3)
ON CONFLICT (behavior_id, answer_value) DO NOTHING;

COMMIT;

-- =============================================================================
-- Verification
--
--   SET app.is_internal = 'on';
--   SELECT s.display_order, s.label, s.score_category,
--          count(*) AS questions
--   FROM behaviors b JOIN rubric_sections s ON s.id = b.section_id
--   GROUP BY s.display_order, s.label, s.score_category
--   ORDER BY s.display_order;
--
--   SELECT count(*) FROM behavior_answers;
--   SELECT count(*) FROM behavior_answers WHERE ftc_flag IS NOT NULL;
-- =============================================================================
