-- ==========================================================================
-- 013b_rubric_behaviors.sql  —  five clients, part B of D
--
-- Possible points per question per client, taken from the live data.
--
-- Run parts A, B, C and D in order. Each is its own transaction.
-- ==========================================================================

BEGIN;

INSERT INTO rubric_behaviors (rubric_id, behavior_id, possible_points, answered_by)
SELECT r.id, b.id, v.pts, 'reviewer'
FROM (VALUES
  ('DOUG', 'At the beginning of your conversation, did they ask questions about you or your reason for calling?', 2.0),
  ('DOUG', 'Did anyone check back with you while you were on hold?', 1.0),
  ('DOUG', 'Did the call seem rushed or hurried?', 1.0),
  ('DOUG', 'Did the professional ask your relationship to the decedent/your loved one?', 1.0),
  ('DOUG', 'Did the professional express condolences and/or empathetic statements?', 2.0),
  ('DOUG', 'Did the professional provide their name?', 3.0),
  ('DOUG', 'Did they ask for permission to place you on hold?', 2.0),
  ('DOUG', 'Did they ask for the name of your loved one?', 2.0),
  ('DOUG', 'Did they ask for your email address?', 2.0),
  ('DOUG', 'Did they ask for your location or the location of your loved one?', 1.0),
  ('DOUG', 'Did they ask for your name?', 4.0),
  ('DOUG', 'Did they ask for your phone number?', 2.0),
  ('DOUG', 'Did they ask how you heard of them, or whether you had prior interactions with their firm?', 1.0),
  ('DOUG', 'Did they ask if the death had occurred?', 2.0),
  ('DOUG', 'Did they ask if you had any other questions?', 2.0),
  ('DOUG', 'Did they ask you about what services you are interested in?', 2.0),
  ('DOUG', 'Did they attempt to set an appointment or "close the sale"?', 2.0),
  ('DOUG', 'Did they end the call with a clear, proper end greeting? (i.e., Goodbye, Take care, Thank you)', 3.0),
  ('DOUG', 'Did they explain what was included in the prices they provided?', 2.0),
  ('DOUG', 'Did they explain why they were placing you on hold, or set expectations for the hold?', 1.0),
  ('DOUG', 'Did they express gratitude for your call?', 2.0),
  ('DOUG', 'Did they have a proper greeting?', 4.0),
  ('DOUG', 'Did they have any poor phone behaviors?', 3.0),
  ('DOUG', 'Did they lead with direct cremation?', 1.0),
  ('DOUG', 'Did they mention any of their competitors at any point during the call?', 1.0),
  ('DOUG', 'Did they offer a value statement or explain why their business/service is unique?', 2.0),
  ('DOUG', 'Did they offer multiple service options?', 1.0),
  ('DOUG', 'Did they offer to call you back at a later time to follow up?', 1.0),
  ('DOUG', 'Did they offer to mail or email information to you?', 1.0),
  ('DOUG', 'Did they provide a call to action? (i.e., Call us back if you have any questions)', 1.0),
  ('DOUG', 'Did they provide enough information?', 2.0),
  ('DOUG', 'Did they provide pricing?', 3.0),
  ('DOUG', 'Did they provide the lowest cost option first?', 0),
  ('DOUG', 'Did they provide their direct phone number or email before they ended the call?', 1.0),
  ('DOUG', 'Did they refer to their website?', 1.0),
  ('DOUG', 'Did they repeat their name before they ended the call?', 1.0),
  ('DOUG', 'Did they seem educated and knowledgable about the services they offered?', 1.0),
  ('DOUG', 'Did they seem prepared?', 3.0),
  ('DOUG', 'Did they show sincere concern?', 2.0),
  ('DOUG', 'Did they use industry jargon or legalese that was unfamiliar to you?', 1.0),
  ('DOUG', 'Did they use your name in conversation?', 2.0),
  ('DOUG', 'Did this call meet your expectations?', 3.0),
  ('DOUG', 'Did you have to repeat any information to the new professional?', 2.0),
  ('DOUG', 'Did you receive an email from the professional?', 2.0),
  ('DOUG', 'How long before Callback?', 2.0),
  ('DOUG', 'How long were you on hold?', 5.0),
  ('DOUG', 'How many prompts did you have to go through to reach a live representative?', 2.0),
  ('DOUG', 'How many times did the phone ring?', 2.0),
  ('DOUG', 'How would you describe their phone etiquette?', 0),
  ('DOUG', 'Immediate abrupt hold?', 1.0),
  ('DOUG', 'Is this a complete call', 0),
  ('DOUG', 'Reviewer Name', 0),
  ('DOUG', 'Transferred more than once?', 2.0),
  ('DOUG', 'Was it easy to reach the right professional?', 5.0),
  ('DOUG', 'Were any of your call attempts answered by an automated message?', 2.0),
  ('DOUG', 'Were the clear and concise?', 3.0),
  ('DOUG', 'Were there multiple attempts to reach a professional?', 5.0),
  ('DOUG', 'Were they articulate and easy to understand?', 2.0),
  ('DOUG', 'Were you placed on hold or transferred at any point within the call?', 5.0),
  ('DOUG', 'Were you transferred to voicemail or a live agent?', 2.0),
  ('DOUG', 'When describing services, did they attempt to upsell by offering additional services like catering or memorialization merchandise, casket or urn options?', 1.0),
  ('DOUG', 'Why did you have to make multiple attempts to reach a professional?', 0),
  ('DOUG', 'Would you hire this company?', 2.0),
  ('DOUG', 'Would you hire this person?', 2.0),
  ('DOUG', 'Would you trust them?', 2.0),
  ('DPX', 'At the beginning of your conversation, did they ask questions about you or your reason for calling?', 2.0),
  ('DPX', 'Did anyone check back with you while you were on hold?', 1.0),
  ('DPX', 'Did the call seem rushed or hurried?', 1.0),
  ('DPX', 'Did the professional ask your relationship to the decedent/your loved one?', 1.0),
  ('DPX', 'Did the professional express condolences and/or empathetic statements?', 2.0),
  ('DPX', 'Did the professional provide their name?', 3.0),
  ('DPX', 'Did they ask for permission to place you on hold?', 2.0),
  ('DPX', 'Did they ask for the name of your loved one?', 2.0),
  ('DPX', 'Did they ask for your email address?', 2.0),
  ('DPX', 'Did they ask for your location or the location of your loved one?', 1.0),
  ('DPX', 'Did they ask for your name?', 4.0),
  ('DPX', 'Did they ask for your phone number?', 2.0),
  ('DPX', 'Did they ask how you heard of them, or whether you had prior interactions with their firm?', 1.0),
  ('DPX', 'Did they ask if the death had occurred?', 2.0),
  ('DPX', 'Did they ask if you had any other questions?', 2.0),
  ('DPX', 'Did they ask you about what services you are interested in?', 2.0),
  ('DPX', 'Did they attempt to set an appointment or "close the sale"?', 2.0),
  ('DPX', 'Did they end the call with a clear, proper end greeting? (i.e., Goodbye, Take care, Thank you)', 3.0),
  ('DPX', 'Did they explain what was included in the prices they provided?', 2.0),
  ('DPX', 'Did they explain why they were placing you on hold, or set expectations for the hold?', 1.0),
  ('DPX', 'Did they express gratitude for your call?', 2.0),
  ('DPX', 'Did they have a proper greeting?', 4.0),
  ('DPX', 'Did they have any poor phone behaviors?', 3.0),
  ('DPX', 'Did they lead with direct cremation?', 1.0),
  ('DPX', 'Did they mention any of their competitors at any point during the call?', 1.0),
  ('DPX', 'Did they offer a value statement or explain why their business/service is unique?', 2.0),
  ('DPX', 'Did they offer multiple service options?', 1.0),
  ('DPX', 'Did they offer to call you back at a later time to follow up?', 1.0),
  ('DPX', 'Did they offer to mail or email information to you?', 1.0),
  ('DPX', 'Did they provide a call to action? (i.e., Call us back if you have any questions)', 1.0),
  ('DPX', 'Did they provide enough information?', 2.0),
  ('DPX', 'Did they provide pricing?', 3.0),
  ('DPX', 'Did they provide the lowest cost option first?', 0),
  ('DPX', 'Did they provide their direct phone number or email before they ended the call?', 1.0),
  ('DPX', 'Did they refer to their website?', 1.0),
  ('DPX', 'Did they repeat their name before they ended the call?', 1.0),
  ('DPX', 'Did they seem educated and knowledgable about the services they offered?', 1.0),
  ('DPX', 'Did they seem prepared?', 3.0),
  ('DPX', 'Did they show sincere concern?', 2.0),
  ('DPX', 'Did they use industry jargon or legalese that was unfamiliar to you?', 1.0),
  ('DPX', 'Did they use your name in conversation?', 2.0),
  ('DPX', 'Did this call meet your expectations?', 3.0),
  ('DPX', 'Did you have to repeat any information to the new professional?', 2.0),
  ('DPX', 'Did you receive an email from the professional?', 2.0),
  ('DPX', 'How long before Callback?', 2.0),
  ('DPX', 'How long were you on hold?', 5.0),
  ('DPX', 'How many times did the phone ring?', 2.0),
  ('DPX', 'Immediate abrupt hold?', 1.0),
  ('DPX', 'Is this a complete call', 0),
  ('DPX', 'Reviewer Name', 0),
  ('DPX', 'Transferred more than once?', 2.0),
  ('DPX', 'Was it easy to reach the right professional?', 5.0),
  ('DPX', 'Were any of your call attempts answered by an automated message?', 2.0),
  ('DPX', 'Were the clear and concise?', 3.0),
  ('DPX', 'Were there multiple attempts to reach a professional?', 5.0),
  ('DPX', 'Were they articulate and easy to understand?', 2.0),
  ('DPX', 'Were you placed on hold or transferred at any point within the call?', 5.0),
  ('DPX', 'Were you transferred to voicemail or a live agent?', 2.0),
  ('DPX', 'When describing services, did they attempt to upsell by offering additional services like catering or memorialization merchandise, casket or urn options?', 1.0),
  ('DPX', 'Why did you have to make multiple attempts to reach a professional?', 0),
  ('DPX', 'Would you hire this company?', 2.0),
  ('DPX', 'Would you hire this person?', 2.0),
  ('DPX', 'Would you trust them?', 2.0),
  ('GIV', 'At the beginning of your conversation, did they ask questions about you or your reason for calling?', 2.0),
  ('GIV', 'Did anyone check back with you while you were on hold?', 1.0),
  ('GIV', 'Did the call seem rushed or hurried?', 1.0),
  ('GIV', 'Did the professional ask your relationship to the decedent/your loved one?', 1.0),
  ('GIV', 'Did the professional express condolences and/or empathetic statements?', 2.0),
  ('GIV', 'Did the professional provide their name?', 3.0),
  ('GIV', 'Did they ask for permission to place you on hold?', 2.0),
  ('GIV', 'Did they ask for the name of your loved one?', 2.0),
  ('GIV', 'Did they ask for your email address?', 2.0),
  ('GIV', 'Did they ask for your location or the location of your loved one?', 1.0),
  ('GIV', 'Did they ask for your name?', 4.0),
  ('GIV', 'Did they ask for your phone number?', 2.0),
  ('GIV', 'Did they ask how you heard of them, or whether you had prior interactions with their firm?', 1.0),
  ('GIV', 'Did they ask if the death had occurred?', 2.0),
  ('GIV', 'Did they ask if you had any other questions?', 2.0),
  ('GIV', 'Did they ask you about what services you are interested in?', 2.0),
  ('GIV', 'Did they attempt to set an appointment or "close the sale"?', 2.0),
  ('GIV', 'Did they end the call with a clear, proper end greeting? (i.e., Goodbye, Take care, Thank you)', 3.0),
  ('GIV', 'Did they explain what was included in the prices they provided?', 2.0),
  ('GIV', 'Did they explain why they were placing you on hold, or set expectations for the hold?', 1.0),
  ('GIV', 'Did they express gratitude for your call?', 2.0),
  ('GIV', 'Did they have a proper greeting?', 4.0),
  ('GIV', 'Did they have any poor phone behaviors?', 3.0),
  ('GIV', 'Did they lead with direct cremation?', 1.0),
  ('GIV', 'Did they mention any of their competitors at any point during the call?', 1.0),
  ('GIV', 'Did they offer a value statement or explain why their business/service is unique?', 2.0),
  ('GIV', 'Did they offer multiple service options?', 1.0),
  ('GIV', 'Did they offer to call you back at a later time to follow up?', 1.0),
  ('GIV', 'Did they offer to mail or email information to you?', 1.0),
  ('GIV', 'Did they provide a call to action? (i.e., Call us back if you have any questions)', 1.0),
  ('GIV', 'Did they provide enough information?', 2.0),
  ('GIV', 'Did they provide pricing?', 3.0),
  ('GIV', 'Did they provide the lowest cost option first?', 0),
  ('GIV', 'Did they provide their direct phone number or email before they ended the call?', 1.0),
  ('GIV', 'Did they refer to their website?', 1.0),
  ('GIV', 'Did they repeat their name before they ended the call?', 1.0),
  ('GIV', 'Did they seem educated and knowledgable about the services they offered?', 1.0),
  ('GIV', 'Did they seem prepared?', 3.0),
  ('GIV', 'Did they show sincere concern?', 2.0),
  ('GIV', 'Did they use industry jargon or legalese that was unfamiliar to you?', 1.0),
  ('GIV', 'Did they use your name in conversation?', 2.0),
  ('GIV', 'Did this call meet your expectations?', 3.0),
  ('GIV', 'Did you have to repeat any information to the new professional?', 2.0),
  ('GIV', 'Did you receive an email from the professional?', 2.0),
  ('GIV', 'How long before Callback?', 2.0),
  ('GIV', 'How long were you on hold?', 5.0),
  ('GIV', 'How many times did the phone ring?', 2.0),
  ('GIV', 'How would you describe their phone etiquette?', 0),
  ('GIV', 'Immediate abrupt hold?', 1.0),
  ('GIV', 'Is this a complete call', 0),
  ('GIV', 'Reviewer Name', 0),
  ('GIV', 'Transferred more than once?', 2.0),
  ('GIV', 'Was it easy to reach the right professional?', 5.0),
  ('GIV', 'Were any of your call attempts answered by an automated message?', 2.0),
  ('GIV', 'Were the clear and concise?', 3.0),
  ('GIV', 'Were there multiple attempts to reach a professional?', 5.0),
  ('GIV', 'Were they articulate and easy to understand?', 2.0),
  ('GIV', 'Were you placed on hold or transferred at any point within the call?', 5.0),
  ('GIV', 'Were you transferred to voicemail or a live agent?', 2.0),
  ('GIV', 'When describing services, did they attempt to upsell by offering additional services like catering or memorialization merchandise, casket or urn options?', 1.0),
  ('GIV', 'Why did you have to make multiple attempts to reach a professional?', 0),
  ('GIV', 'Would you hire this company?', 2.0),
  ('GIV', 'Would you hire this person?', 2.0),
  ('GIV', 'Would you trust them?', 2.0),
  ('PPD', 'At the beginning of your conversation, did they ask questions about you or your reason for calling?', 2.0),
  ('PPD', 'At the end of the call, did they thank you for calling them?', 2.0),
  ('PPD', 'Did anyone check back with you while you were on hold?', 0),
  ('PPD', 'Did the call seem rushed or hurried?', 1.0),
  ('PPD', 'Did the professional ask your relationship to the decedent/your loved one?', 1.0),
  ('PPD', 'Did the professional attempt to upsell you on a product or service?', 0),
  ('PPD', 'Did the professional express condolences and/or empathetic statements?', 2.0),
  ('PPD', 'Did the professional express condolences? i.e. "I''m sorry to hear that your family member is not doing well."', 2.0),
  ('PPD', 'Did the professional have a proper greeting?', 4.0),
  ('PPD', 'Did the professional provide their name?', 3.0),
  ('PPD', 'Did they ask for permission to place you on hold?', 2.0),
  ('PPD', 'Did they ask for the name of your loved one?', 2.0),
  ('PPD', 'Did they ask for your email address?', 2.0),
  ('PPD', 'Did they ask for your location or the location of your loved one?', 1.0),
  ('PPD', 'Did they ask for your name?', 4.0),
  ('PPD', 'Did they ask for your phone number?', 2.0),
  ('PPD', 'Did they ask how you heard about their business?', 1.0),
  ('PPD', 'Did they ask how you heard of them, or whether you had prior interactions with their firm?', 1.0),
  ('PPD', 'Did they ask if the death had occurred?', 2.0),
  ('PPD', 'Did they ask if you had any other questions?', 2.0),
  ('PPD', 'Did they ask if you had any relevant affiliations or memberships? (i.e. Military, Non-profit, Discount programs)', 0),
  ('PPD', 'Did they ask if you had pre-arrangements on file, or had utilized their services in the past?', 0),
  ('PPD', 'Did they ask if you had visited their location or utilized their services in the past?', 1.0),
  ('PPD', 'Did they ask you about what services you are interested in?', 2.0),
  ('PPD', 'Did they attempt to set an appointment or "close the sale"?', 2.0),
  ('PPD', 'Did they attempt to set an appointment, invite you to visit their location, or bring your loved one into their care?', 2.0),
  ('PPD', 'Did they describe any requirements or regulations related to their products or services?', 0),
  ('PPD', 'Did they end the call with a clear, proper end greeting? (i.e., Goodbye, Take care, Thank you)', 3.0),
  ('PPD', 'Did they explain what was included in the prices they provided?', 2.0),
  ('PPD', 'Did they explain why their business is unique?', 2.0),
  ('PPD', 'Did they explain why they were placing you on hold, or set expectations for the hold?', 1.0),
  ('PPD', 'Did they express gratitude for your call?', 2.0),
  ('PPD', 'Did they have a proper greeting?', 4.0),
  ('PPD', 'Did they have any poor phone behaviors?', 3.0),
  ('PPD', 'Did they have any poor phone behaviors? (i.e. Vocal fry, uptalk, "Um," mouth noises)', 3.0),
  ('PPD', 'Did they lead with direct cremation?', 1.0),
  ('PPD', 'Did they mention any of their competitors at any point during the call?', 1.0),
  ('PPD', 'Did they mention budget, financing or insurance?', 0),
  ('PPD', 'Did they offer a value statement or explain why their business/service is unique?', 2.0),
  ('PPD', 'Did they offer multiple service options?', 2.0),
  ('PPD', 'Did they offer to call you back at a later time to follow up?', 1.0),
  ('PPD', 'Did they offer to mail or email information to you?', 2.0),
  ('PPD', 'Did they provide a call to action? (i.e., Call us back if you have any questions)', 1.0),
  ('PPD', 'Did they provide enough information?', 2.0),
  ('PPD', 'Did they provide pricing?', 3.0),
  ('PPD', 'Did they provide the lowest cost option first?', 0),
  ('PPD', 'Did they provide their direct phone number or email before they ended the call?', 1.0),
  ('PPD', 'Did they refer to their website?', 1.0),
  ('PPD', 'Did they repeat their name before they ended the call?', 1.0),
  ('PPD', 'Did they seem educated and knowledgable about the services they offered?', 1.0),
  ('PPD', 'Did they seem prepared?', 3.0),
  ('PPD', 'Did they show sincere concern?', 2.0),
  ('PPD', 'Did they sound comfortable and confident with providing service information and pricing?', 1.0),
  ('PPD', 'Did they use industry jargon or legalese that was unfamiliar to you?', 1.0),
  ('PPD', 'Did they use your name in conversation?', 2.0),
  ('PPD', 'Did this call meet your expectations?', 3.0),
  ('PPD', 'Did you have to repeat any information to the new professional?', 2.0),
  ('PPD', 'Did you have to repeat any of your information to the new professional?', 0),
  ('PPD', 'Did you receive an email from the professional?', 2.0),
  ('PPD', 'How long before Callback?', 2.0),
  ('PPD', 'How long were you on hold?', 0),
  ('PPD', 'How many attempts did it take to reach a professional who could answer your questions?', 5.0),
  ('PPD', 'How many prompts did you have to go through before you were transferred to a live representative?', 2.0),
  ('PPD', 'How many prompts did you have to go through to reach a live representative?', 2.0),
  ('PPD', 'How many times did the phone ring?', 2.0),
  ('PPD', 'How would you describe their phone etiquette?', 0),
  ('PPD', 'If a professional was unavailable to answer your questions, how did the receptionist handle the situation?', 0),
  ('PPD', 'Immediate abrupt hold?', 1.0),
  ('PPD', 'Is this a complete call', 0),
  ('PPD', 'Please enter the name of the professional that you spoke with.', 0),
  ('PPD', 'Reviewer Name', 0),
  ('PPD', 'Script Type', 0),
  ('PPD', 'Transferred more than once?', 2.0),
  ('PPD', 'Was it easy to reach the right professional?', 5.0),
  ('PPD', 'Was there any music or message on hold?', 0),
  ('PPD', 'Were any of your call attempts answered by an automated message?', 2.0),
  ('PPD', 'Were any of your call attempts answered initially by an automated message?', 2.0),
  ('PPD', 'Were the clear and concise?', 3.0),
  ('PPD', 'Were there multiple attempts to reach a professional?', 5.0),
  ('PPD', 'Were they articulate and easy to understand?', 2.0),
  ('PPD', 'Were you placed on hold and/or transferred more than once?', 2.0),
  ('PPD', 'Were you placed on hold before you had the opportunity to ask your question?', 0),
  ('PPD', 'Were you placed on hold or transferred at any point within the call?', 5.0),
  ('PPD', 'Were you transferred to voicemail or a live agent?', 2.0),
  ('PPD', 'Were you transferred to voicemail, or to a live agent?', 0),
  ('PPD', 'What did they say regarding their competitor?', 0),
  ('PPD', 'What was the cost for FIRST service/package they offered?', 0),
  ('PPD', 'When describing services, did they attempt to upsell by offering additional services like catering or memorialization merchandise, casket or urn options?', 1.0),
  ('PPD', 'When describing services, did they give a reason for their value?', 0),
  ('PPD', 'Why did you have to make multiple attempts to reach a professional?', 0),
  ('PPD', 'Would you hire this company?', 2.0),
  ('PPD', 'Would you hire this person?', 2.0),
  ('PPD', 'Would you trust them?', 2.0),
  ('PPD', 'custom_fields_brand_parent_company', 0),
  ('PPD', 'custom_fields_client_name', 0),
  ('PPD', 'custom_fields_competitor', 0),
  ('PPD', 'custom_fields_did_they_seem_prepared', 3.0),
  ('PPD', 'custom_fields_director', 0),
  ('PPD', 'custom_fields_ease_of_reaching_right_person', 5.0),
  ('PPD', 'custom_fields_enough_information', 2.0),
  ('PPD', 'custom_fields_etiquette_adjectives', 0),
  ('PPD', 'custom_fields_expectations', 3.0),
  ('PPD', 'custom_fields_final_impression', 0),
  ('PPD', 'custom_fields_how_would_you_rate_the_call', 5.0),
  ('PPD', 'custom_fields_is_this_a_complete_call', 0),
  ('PPD', 'custom_fields_location_type', 0),
  ('PPD', 'custom_fields_package_type', 0),
  ('PPD', 'custom_fields_pre_need_or_at_need_script', 0),
  ('PPD', 'custom_fields_professional_name', 0),
  ('PPD', 'custom_fields_sincere_concern', 2.0),
  ('PPD', 'custom_fields_value_statement', 0),
  ('PPD', 'custom_fields_website', 0),
  ('PPD', 'custom_fields_were_they_clear_concise', 3.0),
  ('PPD', 'custom_fields_would_you_hire_this_company', 2.0),
  ('PPD', 'custom_fields_would_you_hire_this_person', 2.0),
  ('PPD', 'custom_fields_would_you_trust_them', 2.0),
  ('WHIT', 'At the beginning of your conversation, did they ask questions about you or your reason for calling?', 2.0),
  ('WHIT', 'Did anyone check back with you while you were on hold?', 1.0),
  ('WHIT', 'Did the call seem rushed or hurried?', 1.0),
  ('WHIT', 'Did the professional ask your relationship to the decedent/your loved one?', 1.0),
  ('WHIT', 'Did the professional express condolences and/or empathetic statements?', 2.0),
  ('WHIT', 'Did the professional provide their name?', 3.0),
  ('WHIT', 'Did they ask for permission to place you on hold?', 2.0),
  ('WHIT', 'Did they ask for the name of your loved one?', 2.0),
  ('WHIT', 'Did they ask for your email address?', 2.0),
  ('WHIT', 'Did they ask for your location or the location of your loved one?', 1.0),
  ('WHIT', 'Did they ask for your name?', 4.0),
  ('WHIT', 'Did they ask for your phone number?', 2.0),
  ('WHIT', 'Did they ask how you heard of them, or whether you had prior interactions with their firm?', 1.0),
  ('WHIT', 'Did they ask if the death had occurred?', 2.0),
  ('WHIT', 'Did they ask if you had any other questions?', 2.0),
  ('WHIT', 'Did they ask you about what services you are interested in?', 2.0),
  ('WHIT', 'Did they attempt to set an appointment or "close the sale"?', 2.0),
  ('WHIT', 'Did they end the call with a clear, proper end greeting? (i.e., Goodbye, Take care, Thank you)', 3.0),
  ('WHIT', 'Did they explain what was included in the prices they provided?', 2.0),
  ('WHIT', 'Did they explain why they were placing you on hold, or set expectations for the hold?', 1.0),
  ('WHIT', 'Did they express gratitude for your call?', 2.0),
  ('WHIT', 'Did they have a proper greeting?', 4.0),
  ('WHIT', 'Did they have any poor phone behaviors?', 3.0),
  ('WHIT', 'Did they lead with direct cremation?', 1.0),
  ('WHIT', 'Did they mention any of their competitors at any point during the call?', 1.0),
  ('WHIT', 'Did they offer a value statement or explain why their business/service is unique?', 2.0),
  ('WHIT', 'Did they offer multiple service options?', 1.0),
  ('WHIT', 'Did they offer to call you back at a later time to follow up?', 1.0),
  ('WHIT', 'Did they offer to mail or email information to you?', 1.0),
  ('WHIT', 'Did they provide a call to action? (i.e., Call us back if you have any questions)', 1.0),
  ('WHIT', 'Did they provide enough information?', 2.0),
  ('WHIT', 'Did they provide pricing?', 3.0),
  ('WHIT', 'Did they provide the lowest cost option first?', 0),
  ('WHIT', 'Did they provide their direct phone number or email before they ended the call?', 1.0),
  ('WHIT', 'Did they refer to their website?', 1.0),
  ('WHIT', 'Did they repeat their name before they ended the call?', 1.0),
  ('WHIT', 'Did they seem educated and knowledgable about the services they offered?', 1.0),
  ('WHIT', 'Did they seem prepared?', 3.0),
  ('WHIT', 'Did they show sincere concern?', 2.0),
  ('WHIT', 'Did they use industry jargon or legalese that was unfamiliar to you?', 1.0),
  ('WHIT', 'Did they use your name in conversation?', 2.0),
  ('WHIT', 'Did this call meet your expectations?', 3.0),
  ('WHIT', 'Did you have to repeat any information to the new professional?', 2.0),
  ('WHIT', 'Did you receive an email from the professional?', 2.0),
  ('WHIT', 'How long were you on hold?', 5.0),
  ('WHIT', 'How many prompts did you have to go through to reach a live representative?', 2.0),
  ('WHIT', 'How many times did the phone ring?', 2.0),
  ('WHIT', 'How would you describe their phone etiquette?', 0),
  ('WHIT', 'Immediate abrupt hold?', 1.0),
  ('WHIT', 'Is this a complete call', 0),
  ('WHIT', 'Reviewer Name', 0),
  ('WHIT', 'Transferred more than once?', 2.0),
  ('WHIT', 'Was it easy to reach the right professional?', 5.0),
  ('WHIT', 'Were any of your call attempts answered by an automated message?', 2.0),
  ('WHIT', 'Were the clear and concise?', 3.0),
  ('WHIT', 'Were there multiple attempts to reach a professional?', 5.0),
  ('WHIT', 'Were they articulate and easy to understand?', 2.0),
  ('WHIT', 'Were you placed on hold or transferred at any point within the call?', 5.0),
  ('WHIT', 'Were you transferred to voicemail or a live agent?', 2.0),
  ('WHIT', 'When describing services, did they attempt to upsell by offering additional services like catering or memorialization merchandise, casket or urn options?', 1.0),
  ('WHIT', 'Would you hire this company?', 2.0),
  ('WHIT', 'Would you hire this person?', 2.0),
  ('WHIT', 'Would you trust them?', 2.0)
) AS v(code, blabel, pts)
JOIN organizations o ON o.code = v.code
JOIN rubrics r ON r.organization_id = o.id AND r.rubric_type = 'cx'
JOIN behaviors b ON b.label = v.blabel
ON CONFLICT (rubric_id, behavior_id) DO NOTHING;

COMMIT;
